### ISSUE TITLE
Proplem with Android 6.0

### ISSUE THREAD

**Issue by parker87tinh** [codecoding/SQLite4Unity3d#41] opened 2016-04-18 10:42 UTC
Hello.
i have been used this flugin for my project on unity 5.2.2 and its working on android OS smaller 5.0.
Recently i just bought a new device that run on Android 6.0. then i got proplem with null data on android 6.0.
-So do you have any idea about this bug?
Thanks.

**Comment by robertohuertasm** [comment] 2016-04-18 10:45
I though that Androd 6.0 was working ok as per #27 but maybe no one has pointed out any issue until now. Could you be more specific? What kind of error? Stack trace? Context?

**Comment by parker87tinh** [comment] 2016-04-18 10:58
Hello.
Thanks for you answer.
i am using this code to real SQLite file:
#if UNITY_ANDROID 
			var loadDb = new WWW("jar:file://" + Application.dataPath + "!/assets/" + databaseName);  // this is the path to your StreamingAssets in android
			while (!loadDb.isDone) { }  // CAREFUL here, for safety reasons you shouldn't let this while loop unattended, place a timer and error check
			// then save to Application.persistentDataPath
			File.WriteAllBytes(filepath, loadDb.bytes);
==> i thinks the proplem come from path on android 6.0.

Any thought about this?

**Comment by robertohuertasm** [comment] 2016-04-18 11:01
But what's the exception? Can you test the example on this repository in your new device to see what's going on? I mean, just to see if is something specific of your code instead of something caused by the library itself. Thanks! 👍

**Comment by robertohuertasm** [comment] 2016-04-29 08:34
@parker87tinh Any news on this matter?

**Comment by robertohuertasm** [comment] 2016-07-08 08:44
Hi @parker87tinh I will proceed to close this item as I don't have any feedback from you. If you answer to this I will reopen it gladly.

**Closed by robertohuertasm** 2016-07-08 08:44 UTC
