### ISSUE TITLE
Not able to use Select with where constraint 

### ISSUE THREAD

**Issue by pmohansivam** [codecoding/SQLite4Unity3d#50] opened 2016-11-28 14:12 UTC

**Comment by sandolkakos** [comment] 2016-11-28 17:49
Here is an example about how to select a person object by its name:
Person person = personList.Where(x => x.Name = "Name").FirstOrDefault(); // you need to import the using System.Linq to use the Where clause.

**Comment by robertohuertasm** [comment] 2016-11-28 17:52
Closing this as it seems a duplicate of #51. This seems to be less elaborated than #51 that's why I'm closing it even though it was posted before.

**Closed by robertohuertasm** 2016-11-28 17:52 UTC
Labels: duplicate
