### ISSUE TITLE
SQLite4Unit3d doesn't seem to work with Unity Editor (5.0.0f4)  in some Windows 8.1 x64 machines

### ISSUE THREAD

**Issue by mexinsal** [codecoding/SQLite4Unity3d#8] opened 2015-03-28 00:32 UTC
Hi everyone. Previously, I used this plugin in Unity 4.6 and there is no error with Unity Editor. I have tried to change my project to Unity 5 and I have updated your plugin. After I tried to use it, I got the errors when I run my program on Unity Editor which are

"DllNotFoundException: Assets/Plugins/x64/sqlite3.dll
SQLite4Unity3d.SQLiteConnection..ctor (System.String databasePath, SQLiteOpenFlags openFlags, Boolean storeDateTimeAsTicks)
SQLite4Unity3d.Factory.Create (System.String address)
DataService..ctor (System.String DatabaseName) (at Assets/Resources/Scripts/DB/DataService.cs:54)
Menu.gotoMainScene () (at Assets/Resources/Scripts/Menu.cs:154)
UnityEngine.Events.InvokableCall.Invoke (System.Object[] args) (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:110)
UnityEngine.Events.InvokableCallList.Invoke (System.Object[] parameters) (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:574)
UnityEngine.Events.UnityEventBase.Invoke (System.Object[] parameters) (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:716)
UnityEngine.Events.UnityEvent.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnityEvent_0.cs:53)
UnityEngine.UI.Button.Press () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:35)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:44)
UnityEngine.EventSystems.ExecuteEvents.Execute (IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:52)
UnityEngine.EventSystems.ExecuteEvents.Execute[IPointerClickHandler] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.EventFunction`1 functor) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:269)
UnityEngine.EventSystems.EventSystem:Update()
"

and

"Failed to load 'Assets/Plugins/x64/sqlite3.dll' with error 'A dynamic link library (DLL) initialization routine failed.
', GetDllDirectory returned ''. If GetDllDirectory returned non empty path, check that you're using SetDirectoryDll correctly.
"

On the other hand, when I exported it to my Android, it can run perfectly (Both read and write file).

Have anyone here ever got these problems? If you have any ways to solve them, please let me know. I look forward to hearing from you.

Best Regards,

Chanakit

**Comment by mexinsal** [comment] 2015-03-28 00:35
My machine runs on x64 Intel Architecture (i7 4710HQ) with Windows 8.1 Pro x64. I have tried to use another computer for running the project but I still got the same error. Moreover, I tried to uninstall and reinstall the Unity 5 in my machine but I still got the same error.

**Comment by codecoding** [comment] 2015-03-28 16:00
Just for the record. @mexinsal and I have exchanged several mails about his issue. I have to say that I'm unable to reproduce it and it works for me. Is anyone experiencing the same problem? I've tested it in two different machines and it's always working.

@mexinsal maybe you can share your project so I can see what's really happening.

On the other hand, he claims to have tested the Example project in 2 different machines unsuccessfully. I can't see why he's experiencing this issue as my machine has almost identical configuration as his...

**Comment by codecoding** [comment] 2015-04-01 19:52
After some email conversations with @mexinsal he claims to have tested in a friend's machine without any problem. The only machines that cannot read or detect the sqlite3.dll are his. In fact, my setup is very similar to his: Windows 8.1 x64 i7 and I've tried two other machines without any problem.

Please, if any of you is experiencing the same errors let me know.

**Comment by BLOOD585589** [comment] 2015-06-08 13:10
Hi,

I have the same problem 

ArgumentException: The Assembly Sqlite is referenced by SQLite4Unity3d. But the dll is not allowed to be included or could not be found.
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1 alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2 cache, BuildTarget target) (at C:/buildslave/unity/build/Editor/Mono/AssemblyHelper.cs:137)
UnityEditor.AssemblyHelper.FindAssembliesReferencedBy (System.String[] paths, System.String[] foldersToSearch, BuildTarget target) (at C:/buildslave/unity/build/Editor/Mono/AssemblyHelper.cs:172)
UnityEditor.BuildPipeline:BuildPlayer(String[], String, BuildTarget, BuildOptions)
AutoBuilder:PerformWin64Build() (at Assets/Editor/AutoBuilder.cs:167)

**Comment by tetreum** [comment] 2015-10-13 15:42
I'm also having the same problem.
PC: Windows 8.1 x64 i7
Build:
- Editor: PASS
- Windows x86: FAIL (DllNotFoundException)
- Windows x86_64: PASS

**Comment by codecoding** [comment] 2015-10-13 15:49
I can't look at it until tonight but I'm unable to reproduce it... will you be available tonight for a skype connection?

**Comment by tetreum** [comment] 2015-10-13 16:06
I've sent you an email about this too ;)

**Comment by robertohuertasm** [comment] 2016-01-24 14:27
SQLite4Unity3d plugin doesn't need a dll anymore so this may be solved. Feel free to open this thread again if you feel that this is not resolved by the latest version.

**Closed by robertohuertasm** 2016-01-24 14:27 UTC
Labels: question
